config/routes.rb
Rails.application.routes.draw do  

 root 'static_pages#home'
 get    '/sessions/new',   to: 'sessions#new'
 post   '/sessions/new',   to: 'sessions#create'

 delete '/logout',  to: 'sessions#destroy'

resources :users do
    member do
      get :following, :followers
    end
end


resources :sessions
resources :statuses do
	resources :comments,          only: [:create, :destroy]
 end

resources :relationships,       only: [:create, :destroy]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def new
	end
	def create
	end
 def home
    if logged_in?
      @status  = current_user.statuses.build
      @feed_items = current_user.feed.paginate(page: params[:page])    
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% if logged_in? %>
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container"> 
        <div class="navbar-header">            
            <%= link_to "Home", root_path , class: "navbar-brand" %>
        </div>
        <div class="nav navbar-nav navbar-right">
        	<div class="navbar-header">        	
        	<div class="profile-userpichome">
				<div class="right">
					<%= link_to gravatar_for(current_user, size: 50), current_user %><strong><%= current_user.name %></strong>
				</div>	
			</div>			
        </div>          
    </div>
	</div>
</div>

<div class="row profile">
	<div class="col-md-3">
		<div class="profile-sidebar">
			<!-- SIDEBAR USERPIC -->
				
   					
        			<%= render 'info/user_info' %>      			
      		      
      	</div>
     </div>
				
   <div class="col-md-9">
		<%= render 'info/status_form' %>
    	<div class="profile-content">  
      		<h3>Micropost Feed</h3>
      		<%= render 'info/feed' %>
    	</div>
  	</div>
</div>

<% else %>
  <div id="hello" class="center jumbotron">
    <h1>Welcome to the DDApp</h1>

    
    <br>
    <br><br><br><br><br><br><br><br><br>
    <%= link_to "Login now!", new_session_path, class: "btn btn-lg btn-primary" %>
  </div>

  
<% end %>