config/routes.rb
Rails.application.routes.draw do  

 root 'static_pages#home'
 get    '/sessions/new',   to: 'sessions#new'
 post   '/sessions/new',   to: 'sessions#create'

 delete '/logout',  to: 'sessions#destroy'

resources :users do
    member do
      get :following, :followers
    end
end


resources :sessions
resources :statuses do
	resources :comments,          only: [:create, :destroy]
 end

resources :relationships,       only: [:create, :destroy]

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
	def new
	end
	def show
		@status = Status.find(params[:id])
		if logged_in?
  		@comment  = current_user.comments.build
      	@feed_items_comment = current_user.feed_comment.paginate(page: params[:page])
      	end
	end
	def create
	    @status = current_user.statuses.build(status_params)
	    if @status.save
	      flash[:success] = "Micropost created!"
	      redirect_to root_url
	    else
	      @feed_items = []
	      render 'static_pages/home'
	    end
	end

	def destroy
  	end

  	

  	private
    def status_params
      params.require(:status).permit(:content)
    end
  

end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_status.html.erb
<li id="status-<%= status.id %>">
<div class="row">
    <div class="col-sm-11">
        <div class="panel panel-white post panel-shadow">
            <div class="post-heading">
                <div class="pull-left image">
                    <div class="profile-userpic3">
                    <%= link_to gravatar_for(status.user, size: 50), status.user, class: "pull-left image" %>
                    </div>
                </div>
                <div class="pull-left meta">
                  
                    <h4 class="user"> <%= link_to status.user.name, status.user %></h4>
                    
                    <h6 class="text-muted time">Posted <%= time_ago_in_words(status.created_at) %> ago.</h6>
                </div>
            </div> 
            <div class="post-description"> 
                <%= status.content %>
                <div class="stats">
                    <%= link_to 'Read more', status_path(status.id), class: "btn btn-primary stat-item" %>            
                   
                </div>
            </div>
            <div class="post-footer">                
            </div>
        </div>
    </div>
</div>


</li>

app/views/statuses/show.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container"> 
        <div class="navbar-header">            
            <%= link_to "Home", root_path , class: "navbar-brand" %>
        </div>
        <div class="nav navbar-nav navbar-right">
            <div class="navbar-header">         
            <div class="profile-userpichome">
                <div class="right">
                    <%= link_to gravatar_for(current_user, size: 50), current_user %><strong><%= current_user.name %></strong>
                </div>  
            </div>          
        </div>          
    </div>
    </div>
</div>

<div class="row profile">
    <div class="col-md-3">
        <div class="profile-sidebar">
            <!-- SIDEBAR USERPIC -->
                
                    
                    <%= render 'info/user_info' %>                  
                  
        </div>
     </div>

        <div class="profile-content"> 
        <div class="container"> 
        <div class="col-sm-8">
        <div class="panel panel-white post panel-shadow">
            <div class="post-heading">
                <div class="pull-left image">
                    <div class="profile-userpic3">
                    <%= link_to gravatar_for(@status.user, size: 50), @status.user, class: "pull-left image" %>
                    </div>
                </div>
                <div class="pull-left meta">
                  
                    <h4 class="user"> <%= link_to @status.user.name, @status.user %></h4>
                    
                    <h6 class="text-muted time">Posted <%= time_ago_in_words(@status.created_at) %> ago.</h6>
                </div>
            </div> 
            <div class="post-description"> 
                <%= @status.content %>
                <div class="stats">
                  
                    <a href="#" class="btn btn-default stat-item">
                        <i class="fa fa-thumbs-up icon"></i>2
                    </a>
                    <a href="#" class="btn btn-default stat-item">
                        <i class="fa fa-share icon"></i>12
                    </a>
                </div>
            </div>
             <div class="post-footer">
                <div class="input-group">
                    <%= form_for([@status, @status.comments.build]) do |f| %>                 
                    
                    <div class="input-group">
                        <%= f.text_area :content, placeholder: "add a comment", class: "form-control"%>  
                        <%= f.submit "Post", class: "btn btn-success green" %>
                            
                    </div>             
                </div>
                <% end %> 
                <ul class="comments-list">
                   <%= render 'info/feed_comment' %>
 

                </ul>               
               
            </div>
        </div>
    </div>
    </div>
</div>