config/routes.rb
Rails.application.routes.draw do  

 root 'static_pages#home'
 get    '/sessions/new',   to: 'sessions#new'
 post   '/sessions/new',   to: 'sessions#create'

 delete '/logout',  to: 'sessions#destroy'

resources :users do
    member do
      get :following, :followers
    end
end


resources :sessions
resources :statuses do
	resources :comments,          only: [:create, :destroy]
 end

resources :relationships,       only: [:create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
	before_save { email.downcase! }
	has_many :statuses ,dependent: :destroy
   has_many :comments, dependent: :destroy
  has_many :active_relationships,  class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
	validates :name,  presence: true, length: { maximum: 50 }
  	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                  	 format: { with: VALID_EMAIL_REGEX },
                  	 uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  





  	# Defines a proto-feed.
  # See "Following users" for the full implementation.
  # Returns a user's status feed.
  def feed
    following_ids = "SELECT followed_id FROM relationships
                    WHERE  follower_id = :user_id"
    Status.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

  def feed_comment
    following_ids = "SELECT followed_id FROM relationships
                    WHERE  follower_id = :user_id"
    Comment.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

  # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
                                        :following, :followers]

  	def show
     		 @user = User.find(params[:id])
         @statuses = @user.statuses.paginate(page: params[:page])
         @comments = @user.comments.paginate(page: params[:page])

  	end

   def index
    @users = User.paginate(page: params[:page])
  end

  	def new
  		 @user = User.new
  	end

  	def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
    	flash[:success] = "Welcome to your Home page !!!"
     	redirect_to @user
    else
      render 'new'
    end
  end
def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, size: 150)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-success btn-sm" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-danger btn-sm" %>
<% end %>

app/views/users/index.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container"> 
        <div class="navbar-header">            
 			<%= link_to "Home", root_path , class: "navbar-brand" %>
        </div>
        <div class="nav navbar-nav navbar-right">
        	<div class="navbar-header">        	
        	<div class="profile-userpichome">
				<div class="right">
					<%= link_to gravatar_for(current_user, size: 50), current_user %><strong><%= current_user.name %></strong>
				</div>	
			</div>			
        </div>          
    </div>
	</div>
</div>

<div class="col-md-3">
<div class="profile-userpic">
<h1>Result:</h1>
<%= will_paginate %>
<ul class="users">
  <% @users.each do |user| %>
    
      <%= gravatar_for user %>
      <strong><%= link_to user.name, user %></strong>
      
     
  <% end %>
 <%= will_paginate %>
</ul>
</div>	
</div>
<div class="col-md-9">
	<div class="container">

	</div>
</div>

app/views/users/new.html.erb
	<div class="container">
    	<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<div class="panel panel-login">
					<div class="panel-heading">
						<div class="row">							
							<div class="col-xs-12">
								<a href="#" id="register-form-link">Register</a>
							</div>
						</div>
						<hr>
					</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-12">			    
								
								<div id="register-form" style="display: block;">

									<%= form_for(@user) do |f| %>

									<% if @user.errors.any? %>
									  <div id="error_explanation">
									    <div class="alert alert-danger">
									      The form contains <%= pluralize(@user.errors.count, "error") %>.
									    </div>
									    <ul>
									    <% @user.errors.full_messages.each do |msg| %>
									      <li><%= msg %></li>
									    <% end %>
									    </ul>
									  </div>
									<% end %>
									
									<div class="form-group">
										<%= f.label :name %>
      									<%= f.text_field :name, class: "form-control", :placeholder => "Username" %>										
									</div>
									<div class="form-group">
										<%= f.label :email %>
      									<%= f.text_field :email, class: "form-control", :placeholder => "Email Address" %>									
									</div>
									<div class="form-group">										
										<%= f.label :password %>
      									<%= f.password_field :password, class: "form-control", :placeholder => "Password" %>									
									</div>
									<div class="form-group">
										<%= f.label :password_confirmation, "Confirmation" %>
      									<%= f.password_field :password_confirmation, class: "form-control", :placeholder => "Confirm Password" %>							
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">												
												<%= f.submit "Register Now", class: "form-control btn btn-success" %>
											</div>
										</div>
									</div>
									<% end %>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>


  

app/views/users/show.html.erb
   <div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container"> 
        <div class="navbar-header">            
 			<%= link_to "Home", root_path , class: "navbar-brand" %>
        </div>
        <div class="nav navbar-nav navbar-right">
        	<div class="navbar-header">        	
        	<div class="profile-userpichome">
				<div class="right">
					<%= link_to gravatar_for(current_user, size: 50), current_user %><strong><%= current_user.name %></strong>
				</div>	
			</div>			
        </div>          
    </div>
	</div>
</div>


    <div class="row profile">
		<div class="col-md-3">
			<div class="profile-sidebar">
				<!-- SIDEBAR USERPIC -->
				<div class="profile-userpic">
					<div class="abc">
						<%= gravatar_for @user%>
					</div>
					
				</div>
				<!-- END SIDEBAR USERPIC -->
				<!-- SIDEBAR USER TITLE -->
				<div class="profile-usertitle">
					<div class="profile-usertitle-name">
						<%= @user.name %>
					</div>
					 <section class="stats">
     					 <%= render 'info/stats' %>
  					 </section>
					
				</div>
				<!-- END SIDEBAR USER TITLE -->
				<!-- SIDEBAR BUTTONS -->
				<div class="profile-userbuttons">
					<%= render 'follow_form' if logged_in? %>						
				</div>
				<!-- END SIDEBAR BUTTONS -->
				<!-- SIDEBAR MENU -->
				<% if logged_in? %>
				<div class="profile-usermenu">
					<ul class="nav">
						<li class="active">
							<a href="#">							
							Overview </a>
						</li>
						<li>
							<li><%= link_to "Profile", current_user %></li>
						</li>
						<li>
							<li><%= link_to "Search Friends", users_path %></li>
						</li>							
						<li>
							<%= link_to "Log out", logout_path, method: "delete" %>							
						</li>
					</ul>
				</div>
				<% end %>
				<!-- END MENU -->
			</div>
		</div>
		<div class="col-md-9">
		<div class="row">    
    		<div class="col-md-12">
    			<div class="widget-area no-padding blank">
					<div class="status-upload">
						<form>
							<textarea placeholder="What are you doing right now?" ></textarea>
							<ul>
								<li><a title="" data-toggle="tooltip" data-placement="bottom" data-original-title="Audio"><i class="fa fa-music"></i></a></li>
								<li><a title="" data-toggle="tooltip" data-placement="bottom" data-original-title="Video"><i class="fa fa-video-camera"></i></a></li>
								<li><a title="" data-toggle="tooltip" data-placement="bottom" data-original-title="Sound Record"><i class="fa fa-microphone"></i></a></li>
								<li><a title="" data-toggle="tooltip" data-placement="bottom" data-original-title="Picture"><i class="fa fa-picture-o"></i></a></li>
							</ul>
							<button type="submit" class="btn btn-success green"><i class="fa fa-share"></i> Post</button>
						</form>
					</div><!-- Status Upload  -->
				</div><!-- Widget Area -->
			</div>
        
    	</div>			
            <div class="profile-content"> 
            	<div class= "container">          
			   <div class="col-sm-9">
			   	<% if @user.statuses.any? %>
			       <h3>Status (<%= @user.statuses.count %>)</h3>
			      <ol class="statuses">
			        <%= render @statuses %>
			      </ol>
			      <%= will_paginate @statuses %>
			    <% end %>
			  </div>
			  </div>
            </div>
		</div>
	
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Post:</b> <%= @user.statuses.count %></span>
    </section>
    <section class="stats">
      <%= render 'info/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>